# services:
#     # image project
#     app:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         restart: unless-stopped
#         working_dir: /var/www/
#         volumes:
#             - ./:/var/www
#         # depends_on:
#         #     - redis
#         networks:
#             - spring-server

#     # db mysql
#     db:
#         image: mysql:5.7.22
#         restart: unless-stopped
#         environment:
#             MYSQL_DATABASE: ${DB_DATABASE:-laravel}
#             MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
#             MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
#             MYSQL_USER: ${DB_USERNAME:-username}
#         volumes:
#             - ./.docker/mysql/dbdata:/var/lib/mysql
#         ports:
#             - "3388:3306"
#         networks:
#             - laravel

#     # PHPMyAdmin
#     phpmyadmin:
#         image: phpmyadmin/phpmyadmin
#         restart: unless-stopped
#         ports:
#             - "8080:80"
#         environment:
#             PMA_HOST: db
#             PMA_PORT: 3306
#             MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
#         networks:
#             - spring-server

#     app:build:
#       depends_on:
#         - db
#       build: ./server
#       restart: on-failure
#       env_file: ./.env
#       ports:
#         - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#       environment:
#         SPRING_APLICATION_JSON: '{
#           ""
#         }'

# networks:
#     laravel:
#         driver: bridge

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - spring-server-network
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - spring-server-network

  # phpmyadmin:
  #     image: phpmyadmin/phpmyadmin
  #       restart: unless-stopped
  #       ports:
  #           - "8080:80"
  #       environment:
  #           PMA_HOST: db
  #           PMA_PORT: 3306
  #           MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
  #       networks:
  #           - laravel

volumes:
  db:

networks:
  spring-server-network:
    driver: bridge